### ISSUE TITLE
Getting Error on npm run build

### ISSUE THREAD

**Issue by govindgauswami** [benorama/ngrx-demo-apps#12]
i have installed using npm install

now if i run **npm run build** 
getting below error **'rm' is not recognized as an internal or external command,**

**Comment by skygui** [comment]
me too

**Comment by skygui** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'clean' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle ngrx-demo-core@0.0.1~preclean: ngrx-demo-core@0.0.1
6 silly lifecycle ngrx-demo-core@0.0.1~preclean: no script for preclean, continuing
7 info lifecycle ngrx-demo-core@0.0.1~clean: ngrx-demo-core@0.0.1
8 verbose lifecycle ngrx-demo-core@0.0.1~clean: unsafe-perm in lifecycle true
9 verbose lifecycle ngrx-demo-core@0.0.1~clean: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\ionic2\ngrx-demo-apps-master\core\node_modules\.bin;D:\ionic2\ngrx-demo-apps-master\core\node_modules\.bin;C:\Users\skygui\AppData\Local\Yarn\config\link\node_modules\.bin;D:\ionic2\ngrx-demo-apps-master\core\node_modules\.bin;C:\Users\skygui\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Users\skygui\AppData\Local\Yarn\bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Docker\Docker\Resources\bin;D:\Mono\gradle-3.4.1\bin;D:\Python27;D:\Python27\Scripts;C:\Users\skygui\AppData\Roaming\npm;%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Samsung\SamsungLink\AllShare Framework DMS\bin\;D:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;D:\Mono\android-sdk\platform-tools;C:\Users\skygui\AppData\Local\Microsoft\WindowsApps;;C:\Users\skygui\AppData\Roaming\npm;d:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle ngrx-demo-core@0.0.1~clean: CWD: D:\ionic2\ngrx-demo-apps-master\core
11 silly lifecycle ngrx-demo-core@0.0.1~clean: Args: [ '/d /s /c',
11 silly lifecycle   'rm -rf ./aot/* && rm -rf ./dist/* && npm run clean:postbuild' ]
12 silly lifecycle ngrx-demo-core@0.0.1~clean: Returned: code: 1  signal: null
13 info lifecycle ngrx-demo-core@0.0.1~clean: Failed to exec clean script
14 verbose stack Error: ngrx-demo-core@0.0.1 clean: `rm -rf ./aot/* && rm -rf ./dist/* && npm run clean:postbuild`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ngrx-demo-core@0.0.1
16 verbose cwd D:\ionic2\ngrx-demo-apps-master\core
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ngrx-demo-core@0.0.1 clean: `rm -rf ./aot/* && rm -rf ./dist/* && npm run clean:postbuild`
22 error Exit status 1
23 error Failed at the ngrx-demo-core@0.0.1 clean script 'rm -rf ./aot/* && rm -rf ./dist/* && npm run clean:postbuild'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ngrx-demo-core package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rm -rf ./aot/* && rm -rf ./dist/* && npm run clean:postbuild
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ngrx-demo-core
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ngrx-demo-core
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Srini72** [comment]
Hi any update on this facing the same issue

**Comment by jrahulroy** [comment]
For core in package.json, update clean script as below
"clean": "rmdir  /s /q \\aot && rmdir /s /q \\dist && npm run clean:postbuild"

It is an issue with windows, rm doesn't exist in windows.

**Comment by benorama** [comment]
Here is the new solution (much more elegant) for Angular5 and Ionic3 ! https://medium.com/@benorama/sharing-ngrx-based-logic-between-angular5-web-app-and-ionic3-mobile-app-77c19470cccc
